### ISSUE TITLE
Can you implement "suggestedQuality" parameter, video played defaults to lowest quality.

### ISSUE THREAD

**Issue by chewtoys** [GoogleWebComponents/google-youtube-video-wall#14]
https://developers.google.com/youtube/js_api_reference#setPlaybackQuality

**Comment by jeffposnick** [comment]
(This is better suited for the [`<google-youtube>` issue tracker](https://github.com/GoogleWebComponents/google-youtube/issues), but responding here anyway.)

I have a strong aversion to the `setPlaybackQuality()` method in general, and don't think it should be exposed in `<google-youtube>`. As mentioned in the [docs](https://developers.google.com/youtube/js_api_reference#setPlaybackQuality):

```
We recommend that you set the parameter value to default, which instructs YouTube
to select the most appropriate playback quality, which will vary for different users,
videos, systems and other playback conditions.
```

The current YouTube Player does a very good job of automatically detecting the best playback quality and dynamically adapting playback quality on the fly as playback conditions change.

**Comment by chewtoys** [comment]
I disagree, youtube is pretty stupid when it comes to selecting playback quality.

They say it makes the right choice, but it really dosnt, but yeah I will leave a message on < google-youtube >.
